CREATE DATABASE campus;

CREATE TABLE campers(
    id INT primary key AUTO_INCREMENT,
    NOMBRES VARCHAR (50) NOT NULL,
    DIRECCION VARCHAR (50) NOT NULL,
    SKILLS INT,
    INGLES VARCHAR (15),
    SER INT,
    REVIEW VARCHAR (15)
    ESPECIALIDAD VARCHAR (15)
);
